luapath=string.match(GetInfo(35),"^.*\\")
mclpath=GetInfo(67)
include=function(str)
	dofile(luapath..str)
end
loadmod=function(str)
	include("mods\\"..str)
end

loadmclfile=function(str)
		local f=(loadfile(mclpath..str))
		if f~=nil then f() end
end
print("‘ÿ»Î÷–")
loadmod("encrypt.mod")
loadmod("mapper.mod")
loadmod("mudvar.mod")
loadmod("walk.mod")
loadmod("house.mod")
loadmod("loadconfig.mod")
loadmod("hook.mod")
loadmod("system.mod")
loadmod("misc.mod")
loadmod("check.mod")
loadmod("items.mod")
loadmod("pack.mod")
loadmod("status.mod")
loadmod("study.mod")
loadmod("jiqu.mod")
loadmod("alias.mod")
loadmod("search.mod")
loadmod("study.mod")
loadmod("heal.mod")
loadmod("rest.mod")
loadmod("info.mod")
loadmod("npc.mod")
loadmod("kill.mod")
loadmod("fangqi.mod")
loadmod("dropgift.mod")
loadmod("weapon.mod")
loadmod("askyou.mod")
loadmod("event.mod")
loadmod("quest.mod")
loadmod("remote.mod")
if configcmd~=nil then
	configcmd()
end
loadmod("update.mod")

